version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'coco'
      MYSQL_USER: 'coco'
      MYSQL_PASSWORD: 'coco'
      MYSQL_ROOT_PASSWORD: 'coco'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_coco

volumes:
  my-db: